name: salas_beats
description: Marketplace para rentar salas de ensayo y estudios de grabaciÃ³n
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  app_settings: 5.1.1
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  connectivity_plus: ^6.0.5  # Keeping compatible version
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.2  # Updated but compatible
  dio: ^5.3.2
  email_validator: ^2.1.17  # Keeping compatible version
  exif: ^3.1.1
  file_picker: ^8.1.2  # Updated but compatible
  firebase_analytics: ^12.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  firebase_performance: ^0.11.0+1
  firebase_storage: ^13.0.1
  fl_chart: ^0.69.0  # Updated but compatible
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^11.1.0  # Updated but compatible
  flutter_svg: ^2.0.9
  geocoding: ^3.0.0  # Updated but compatible
  geolocator: ^10.1.1  # Compatible version
  go_router: ^14.3.0  # Updated but compatible
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1  # Keeping compatible version
  http: ^1.1.0
  image: ^4.1.7
  image_cropper: ^8.0.2  # Updated but compatible
  image_picker: ^1.0.4
  intl: ^0.20.2
  package_info_plus: ^8.0.2  # Compatible version
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.1  # Updated but compatible
  provider: ^6.1.1
  record: ^6.1.2
  share_plus: ^10.0.3  # Updated but compatible
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.1.2  # Updated but compatible
  table_calendar: ^3.0.9
  timeago: ^3.6.1
  url_launcher: ^6.2.1
  
dev_dependencies:
  flutter_lints: ^4.0.0  # Updated but compatible
  flutter_test:
    sdk: flutter
  # Testing dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.7
  network_image_mock: ^2.1.1
  integration_test:
    sdk: flutter
  # Code coverage
  coverage: ^1.7.2
  
flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700